2020-06-02 12:02:27.793 [error] <0.313.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Redeal.RabbitHandler',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,417}]},{gen_server,init_it,6,...},...]}} in context start_error
2020-06-02 12:02:27.795 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Redeal.RabbitHandler',{'EXIT',{undef,[{'Elixir.Redeal.RabbitHandler',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,385}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,371}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,355}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1171}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,321}]},{gen_server,init_it,...},...]}}}},...} in application_master:init/4 line 138
2020-06-02 12:02:57.923 [error] <0.465.0>@Elixir.Redeal.RabbitHandler:init:22 CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.Redeal.RabbitHandler':init/1 line 22
2020-06-02 12:04:59.924 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-ccfEHo5e7VNpvUZ6yMjTCA">>}}
2020-06-02 12:05:28.385 [error] <0.339.0> Failed to start Ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-06-02 12:16:02.747 [error] <0.63.0> Supervisor {<0.63.0>,user_sup} had child at module user_sup at <0.64.0> exit with reason eio in context child_terminated
2020-06-02 12:16:02.747 [error] <0.63.0> gen_server <0.63.0> terminated with reason: eio
2020-06-02 12:16:02.748 [error] <0.255.0>@lager_console_backend:handle_event:179 gen_event lager_console_backend installed in lager_event terminated with reason: bad argument in call to io:put_chars(user, unicode, [["12",58,"16",58,"02",46,"746"]," ",[],"[","info","] ","SIGTERM received - shutting down","\r\n"]) in lager_console_backend:handle_event/2 line 179
2020-06-02 12:16:02.759 [error] <0.63.0> CRASH REPORT Process <0.63.0> with 0 neighbours exited with reason: eio in gen_server:handle_common_reply/8 line 796
2020-06-02 12:16:02.759 [error] <0.49.0> Supervisor kernel_sup had child user started with user_sup:start() at <0.63.0> exit with reason eio in context child_terminated
2020-06-02 13:01:39.003 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-QteqIOIuLhV1-_wKQxU0cw">>}}
2020-06-02 13:04:25.152 [error] <0.465.0> 'Elixir.Redeal.RabbitHandler' <0.465.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-sAf4Ci2dCKNgJBIPgzvaJQ">>}}
2020-06-02 13:14:00.173 [error] <0.465.0> 'Elixir.Redeal.RabbitHandler' <0.465.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-d9Gys7urERy2j3fVR8nXgg">>}}
2020-06-02 13:15:05.019 [error] <0.460.0> 'Elixir.Redeal.RabbitHandler' <0.460.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-r7KBZ7FCU6pc0xfqzh3z5g">>}}
2020-06-02 13:15:39.884 [error] <0.480.0> CRASH REPORT Process <0.480.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 13:15:39.896 [error] <0.480.0> Cowboy stream 2 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.477.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 13:31:26.444 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-nn1iwbwbX4YKFabLpJwpYA">>}}
2020-06-02 13:37:51.315 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_deliver,<<"got that">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-nn1iwbwbX4YKFabLpJwpYA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"exchange">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<"response">>,timestamp => undefined,type => undefined,user_id => undefined}}
2020-06-02 13:39:03.571 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_deliver,<<"got that">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-nn1iwbwbX4YKFabLpJwpYA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 2,exchange => <<"exchange">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<"response">>,timestamp => undefined,type => undefined,user_id => undefined}}
2020-06-02 13:41:53.251 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_deliver,<<"got that">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-nn1iwbwbX4YKFabLpJwpYA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 3,exchange => <<"exchange">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<"response">>,timestamp => undefined,type => undefined,user_id => undefined}}
2020-06-02 13:41:53.251 [error] <0.442.0> 'Elixir.Redeal.RabbitHandler' <0.442.0> received unexpected message in handle_info/2: {basic_deliver,<<"got that">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-nn1iwbwbX4YKFabLpJwpYA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 4,exchange => <<"exchange">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<"response">>,timestamp => undefined,type => undefined,user_id => undefined}}
2020-06-02 13:50:06.151 [error] <0.465.0> 'Elixir.Redeal.RabbitHandler' <0.465.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-I2G7JEDrGlKr1oYkDQ014g">>}}
2020-06-02 13:50:11.007 [error] <0.465.0> 'Elixir.Redeal.RabbitHandler' <0.465.0> received unexpected message in handle_info/2: {basic_deliver,<<"got that">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-I2G7JEDrGlKr1oYkDQ014g">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"exchange">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<"response">>,timestamp => undefined,type => undefined,user_id => undefined}}
2020-06-02 13:50:11.008 [error] <0.465.0> 'Elixir.Redeal.RabbitHandler' <0.465.0> received unexpected message in handle_info/2: {basic_deliver,<<"got that">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-I2G7JEDrGlKr1oYkDQ014g">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 2,exchange => <<"exchange">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<"response">>,timestamp => undefined,type => undefined,user_id => undefined}}
2020-06-02 13:51:31.221 [error] <0.465.0> gen_server <0.465.0> terminated with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.468.0>},pid => <0.479.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.468.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.237 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.468.0>},pid => <0.479.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.468.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.238 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.465.0> exit with reason {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.468.0>},pid => <0.479.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.468.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68 in context child_terminated
2020-06-02 13:51:31.263 [error] <0.482.0> gen_server <0.482.0> terminated with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.485.0>},pid => <0.494.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.485.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.264 [error] <0.482.0> CRASH REPORT Process <0.482.0> with 0 neighbours crashed with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.485.0>},pid => <0.494.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.485.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.264 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.482.0> exit with reason {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.485.0>},pid => <0.494.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.485.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68 in context child_terminated
2020-06-02 13:51:31.286 [error] <0.497.0> gen_server <0.497.0> terminated with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.500.0>},pid => <0.509.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.500.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.286 [error] <0.497.0> CRASH REPORT Process <0.497.0> with 0 neighbours crashed with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.500.0>},pid => <0.509.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.500.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.286 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.497.0> exit with reason {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.500.0>},pid => <0.509.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.500.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68 in context child_terminated
2020-06-02 13:51:31.308 [error] <0.512.0> gen_server <0.512.0> terminated with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.515.0>},pid => <0.524.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.515.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.309 [error] <0.512.0> CRASH REPORT Process <0.512.0> with 0 neighbours crashed with reason: {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.515.0>},pid => <0.524.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.515.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68
2020-06-02 13:51:31.309 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.512.0> exit with reason {badkey,connection,#{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.515.0>},pid => <0.524.0>},conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.515.0>}}} in 'Elixir.Redeal.RabbitHandler':terminate/2 line 68 in context child_terminated
2020-06-02 13:51:31.309 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.512.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 13:52:38.803 [error] <0.465.0>@Elixir.Redeal.RabbitHandler:handle_info:61 gen_server <0.465.0> terminated with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-60MSU4SEhdVUF_LUQZOHGw">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.822 [error] <0.465.0>@Elixir.Redeal.RabbitHandler:handle_info:61 CRASH REPORT Process <0.465.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-60MSU4SEhdVUF_LUQZOHGw">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.822 [error] <0.336.0>@Elixir.Redeal.RabbitHandler:handle_info:61 Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.465.0> exit with reason no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-60MSU4SEhdVUF_LUQZOHGw">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61 in context child_terminated
2020-06-02 13:52:38.837 [error] <0.482.0>@Elixir.Redeal.RabbitHandler:handle_info:61 gen_server <0.482.0> terminated with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-xfoUa97BPC-EMROiQm-Jsg">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.838 [error] <0.482.0>@Elixir.Redeal.RabbitHandler:handle_info:61 CRASH REPORT Process <0.482.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-xfoUa97BPC-EMROiQm-Jsg">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.838 [error] <0.336.0>@Elixir.Redeal.RabbitHandler:handle_info:61 Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.482.0> exit with reason no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-xfoUa97BPC-EMROiQm-Jsg">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61 in context child_terminated
2020-06-02 13:52:38.862 [error] <0.497.0>@Elixir.Redeal.RabbitHandler:handle_info:61 gen_server <0.497.0> terminated with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-H8M2Q-z8E0nCXrUCeiCV5g">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.864 [error] <0.497.0>@Elixir.Redeal.RabbitHandler:handle_info:61 CRASH REPORT Process <0.497.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-H8M2Q-z8E0nCXrUCeiCV5g">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.864 [error] <0.336.0>@Elixir.Redeal.RabbitHandler:handle_info:61 Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.497.0> exit with reason no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-H8M2Q-z8E0nCXrUCeiCV5g">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61 in context child_terminated
2020-06-02 13:52:38.882 [error] <0.512.0>@Elixir.Redeal.RabbitHandler:handle_info:61 gen_server <0.512.0> terminated with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-zIlDGbNBDrhiFcI-cStLcQ">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.883 [error] <0.512.0>@Elixir.Redeal.RabbitHandler:handle_info:61 CRASH REPORT Process <0.512.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-zIlDGbNBDrhiFcI-cStLcQ">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61
2020-06-02 13:52:38.883 [error] <0.336.0>@Elixir.Redeal.RabbitHandler:handle_info:61 Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.512.0> exit with reason no function clause matching 'Elixir.Redeal.RabbitHandler':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-zIlDGbNBDrhiFcI-cStLcQ">>}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 61 in context child_terminated
2020-06-02 13:52:38.883 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.512.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 13:55:42.691 [error] <0.468.0> gen_server <0.468.0> terminated with reason: socket_closed_unexpectedly
2020-06-02 13:55:42.691 [error] <0.468.0> CRASH REPORT Process <0.468.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 796
2020-06-02 13:55:42.692 [error] <0.466.0> Supervisor {<0.466.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.467.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.468.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-06-02 13:55:42.692 [error] <0.466.0> Supervisor {<0.466.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.467.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.468.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 14:24:10.019 [error] <0.474.0> gen_server <0.474.0> terminated with reason: {socket_error,timeout}
2020-06-02 14:24:10.019 [error] <0.468.0> gen_server <0.468.0> terminated with reason: {socket_error,timeout}
2020-06-02 14:24:10.019 [error] <0.468.0> CRASH REPORT Process <0.468.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 796
2020-06-02 14:24:10.019 [error] <0.466.0> Supervisor {<0.466.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.467.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.468.0> exit with reason {socket_error,timeout} in context child_terminated
2020-06-02 14:24:10.020 [error] <0.466.0> Supervisor {<0.466.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.467.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.468.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 14:46:41.911 [error] <0.483.0> CRASH REPORT Process <0.483.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {deal,<<"got that">>}},[{'Elixir.Jason','encode!',2,[{file,"lib/jason.ex"},{line,150}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,8}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:46:42.057 [error] <0.483.0> Cowboy stream 1 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.482.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {deal,<<"got that">>}},[{'Elixir.Jason','encode!',2,[{file,"lib/jason.ex"},{line,150}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,8}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_cont..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:48:13.324 [error] <0.494.0> CRASH REPORT Process <0.494.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => [{deal,<<"got that">>}]},[{'Elixir.Redeal.RabbitHandler',wait_for_response,0,[{file,"lib/redeal/rabbit_handler.ex"},{line,20}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:48:13.336 [error] <0.494.0> Cowboy stream 1 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.493.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => [{deal,<<"got that">>}]},[{'Elixir.Redeal.RabbitHandler',wait_for_response,0,[{file,"lib/redeal/rabbit_handler.ex"},{line,20}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:48:15.865 [error] <0.501.0> CRASH REPORT Process <0.501.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => [{deal,<<"got that">>}]},[{'Elixir.Redeal.RabbitHandler',wait_for_response,0,[{file,"lib/redeal/rabbit_handler.ex"},{line,20}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:48:15.866 [error] <0.501.0> Cowboy stream 3 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.493.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => [{deal,<<"got that">>}]},[{'Elixir.Redeal.RabbitHandler',wait_for_response,0,[{file,"lib/redeal/rabbit_handler.ex"},{line,20}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:57:19.056 [error] <0.485.0> CRASH REPORT Process <0.485.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => []},[{'Elixir.Redeal.RabbitHandler',wait_for_response,1,[{file,"lib/redeal/rabbit_handler.ex"},{line,19}]},{'Elixir.RedealWeb.DealController',get_one_nt,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,16}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 14:57:19.060 [error] <0.485.0> Cowboy stream 2 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.482.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => []},[{'Elixir.Redeal.RabbitHandler',wait_for_response,1,[{file,"lib/redeal/rabbit_handler.ex"},{line,19}]},{'Elixir.RedealWeb.DealController',get_one_nt,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,16}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 15:09:43.911 [error] emulator Error in process <0.481.0> with exit value:
{badarg,[{erlang,monitor,[process,[{no_ack,'Elixir.True'}]],[]},{'Elixir.AMQP.Channel.ReceiverManager','-spawn_receiver/2-fun-0-',2,[{file,"lib/amqp/channel/receiver_manager.ex"},{line,111}]}]}
2020-06-02 15:09:43.919 [error] <0.478.0> gen_server <0.478.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-06-02 15:09:43.929 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-06-02 15:09:43.930 [error] <0.477.0> Supervisor {<0.477.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52990 -> 127.0.0.1:5672">>,1}) at <0.478.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-06-02 15:09:43.930 [error] <0.477.0> Supervisor {<0.477.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52990 -> 127.0.0.1:5672">>,1}) at <0.478.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 15:10:12.978 [error] <0.465.0>@gen_server:call gen_server 'Elixir.RabbitHandler' terminated with reason: no such process or port in call to gen_server:call(<0.479.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 15:10:12.981 [error] <0.465.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.479.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 15:10:12.982 [error] <0.336.0>@gen_server:call Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.465.0> exit with reason no such process or port in call to gen_server:call(<0.479.0>, {close,200,<<"Goodbye">>}, 60000) in context child_terminated
2020-06-02 15:10:12.995 [error] emulator Error in process <0.499.0> with exit value:
{badarg,[{erlang,monitor,[process,[{no_ack,'Elixir.True'}]],[]},{'Elixir.AMQP.Channel.ReceiverManager','-spawn_receiver/2-fun-0-',2,[{file,"lib/amqp/channel/receiver_manager.ex"},{line,111}]}]}
2020-06-02 15:10:19.522 [error] <0.496.0> gen_server <0.496.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-06-02 15:10:19.524 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-06-02 15:10:19.526 [error] <0.497.0> gen_server <0.497.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.496.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-uOfeFLq2H3eqG2PEKFi8lQ">>,1,false,<<"exchange">>,<<"response">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"Szymon">>}},60000]}} in gen_server2:call/3 line 346
2020-06-02 15:10:19.526 [error] <0.495.0> Supervisor {<0.495.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52997 -> 127.0.0.1:5672">>,1}) at <0.496.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-06-02 15:10:19.526 [error] <0.495.0> Supervisor {<0.495.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:52997 -> 127.0.0.1:5672">>,1}) at <0.496.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 15:10:37.513 [error] <0.485.0>@gen_server:call gen_server 'Elixir.RabbitHandler' terminated with reason: no such process or port in call to gen_server:call(<0.497.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 15:10:37.515 [error] <0.485.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.497.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 15:10:37.520 [error] <0.336.0>@gen_server:call Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.485.0> exit with reason no such process or port in call to gen_server:call(<0.497.0>, {close,200,<<"Goodbye">>}, 60000) in context child_terminated
2020-06-02 15:10:37.543 [error] emulator Error in process <0.522.0> with exit value:
{badarg,[{erlang,monitor,[process,[{no_ack,'Elixir.True'}]],[]},{'Elixir.AMQP.Channel.ReceiverManager','-spawn_receiver/2-fun-0-',2,[{file,"lib/amqp/channel/receiver_manager.ex"},{line,111}]}]}
2020-06-02 15:14:54.938 [error] <0.465.0>@Elixir.Redeal.RabbitHandler:handle_info:90 gen_server 'Elixir.RabbitHandler' terminated with reason: call to undefined function 'Elixir.AMQP.Basic':ack/0 from 'Elixir.Redeal.RabbitHandler':handle_info/2 line 90
2020-06-02 15:14:54.962 [error] <0.465.0>@Elixir.AMQP.Basic:ack CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: call to undefined function 'Elixir.AMQP.Basic':ack()
2020-06-02 15:14:54.963 [error] <0.336.0>@Elixir.AMQP.Basic:ack Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.465.0> exit with reason call to undefined function 'Elixir.AMQP.Basic':ack() in context child_terminated
2020-06-02 15:14:55.000 [error] <0.482.0>@Elixir.Redeal.RabbitHandler:handle_info:90 gen_server 'Elixir.RabbitHandler' terminated with reason: call to undefined function 'Elixir.AMQP.Basic':ack/0 from 'Elixir.Redeal.RabbitHandler':handle_info/2 line 90
2020-06-02 15:14:55.001 [error] <0.482.0>@Elixir.AMQP.Basic:ack CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: call to undefined function 'Elixir.AMQP.Basic':ack()
2020-06-02 15:14:55.002 [error] <0.336.0>@Elixir.AMQP.Basic:ack Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.482.0> exit with reason call to undefined function 'Elixir.AMQP.Basic':ack() in context child_terminated
2020-06-02 15:14:55.036 [error] <0.497.0>@Elixir.Redeal.RabbitHandler:handle_info:90 gen_server 'Elixir.RabbitHandler' terminated with reason: call to undefined function 'Elixir.AMQP.Basic':ack/0 from 'Elixir.Redeal.RabbitHandler':handle_info/2 line 90
2020-06-02 15:14:55.037 [error] <0.497.0>@Elixir.AMQP.Basic:ack CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: call to undefined function 'Elixir.AMQP.Basic':ack()
2020-06-02 15:14:55.037 [error] <0.336.0>@Elixir.AMQP.Basic:ack Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.497.0> exit with reason call to undefined function 'Elixir.AMQP.Basic':ack() in context child_terminated
2020-06-02 15:51:59.276 [error] <0.465.0> gen_server 'Elixir.RabbitHandler' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.297 [error] <0.465.0> CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.298 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.465.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78 in context child_terminated
2020-06-02 15:51:59.311 [error] <0.485.0> gen_server 'Elixir.RabbitHandler' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.312 [error] <0.485.0> CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.313 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.485.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78 in context child_terminated
2020-06-02 15:51:59.326 [error] <0.500.0> gen_server 'Elixir.RabbitHandler' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.327 [error] <0.500.0> CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.327 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.500.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78 in context child_terminated
2020-06-02 15:51:59.340 [error] <0.515.0> gen_server 'Elixir.RabbitHandler' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.341 [error] <0.515.0> CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78
2020-06-02 15:51:59.341 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.515.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<32,32,32,32,32,32,32,10,32,32,32,32,32,32,32,226,153,160,84,50,10,32,32,32,32,32,32,32,226,153,161,84,54,50,10,32,32,32,32,32,32,32,226,153,162,75,74,57,56,50,10,32,32,32,32,32,32,32,226,153,163,84,56,55,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,10,226,153,160,74,57,56,55,52,32,32,32,32,32,32,32,32,226,153,160,75,51,10,226,153,161,56,53,52,32,32,32,32,32,32,32,32,32,32,226,153,161,75,74,57,10,226,153,162,54,32,...>>,...} in 'Elixir.Jason':'decode!'/2 line 78 in context child_terminated
2020-06-02 15:51:59.342 [error] <0.336.0> Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.515.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 15:51:59.494 [error] <0.483.0> CRASH REPORT Process <0.483.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{ets,lookup,[deals,deal],[]},{'Elixir.Redeal.RabbitHandler',wait_for_response,1,[{file,"lib/redeal/rabbit_handler.ex"},{line,19}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 15:51:59.502 [error] <0.483.0> Cowboy stream 1 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.482.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{ets,lookup,[deals,deal],[]},{'Elixir.Redeal.RabbitHandler',wait_for_response,1,[{file,"lib/redeal/rabbit_handler.ex"},{line,19}]},{'Elixir.RedealWeb.DealController',get_random,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 15:52:04.342 [error] <0.343.0> Supervisor 'Elixir.RedealWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.RedealWeb.Endpoint.HTTP']}]) at <0.463.0> exit with reason killed in context shutdown_error
2020-06-02 17:04:55.921 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_atom,[nil,utf8],[]},{'Elixir.RedealWeb.DealController',get_deal,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,8}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 17:04:55.929 [error] <0.488.0> Cowboy stream 1 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.487.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_atom,[nil,utf8],[]},{'Elixir.RedealWeb.DealController',get_deal,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,8}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 17:06:39.149 [error] <0.504.0> CRASH REPORT Process <0.504.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_atom,[nil,utf8],[]},{'Elixir.RedealWeb.DealController',get_deal,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,8}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 17:06:39.149 [error] <0.504.0> Cowboy stream 1 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.503.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_atom,[nil,utf8],[]},{'Elixir.RedealWeb.DealController',get_deal,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,8}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 17:07:49.643 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_atom,[nil,utf8],[]},{'Elixir.RedealWeb.DealController',get_deal,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 17:07:49.649 [error] <0.478.0> Cowboy stream 1 with ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' and connection process <0.477.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_atom,[nil,utf8],[]},{'Elixir.RedealWeb.DealController',get_deal,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,7}]},{'Elixir.RedealWeb.DealController',action,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},{'Elixir.RedealWeb.DealController',phoenix_controller_pipeline,2,[{file,"lib/redeal_web/controllers/deal_controller.ex"},{line,1}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':exit_on_error/4 line 130
2020-06-02 17:08:40.190 [error] <0.485.0>@lists:reverse:147 CRASH REPORT Process <0.485.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(nil) line 147
2020-06-02 17:08:40.191 [error] <0.482.0>@lists:reverse:147 Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.48>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:55550 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.485.0> exit with reason no function clause matching lists:reverse(nil) line 147 in context child_terminated
2020-06-02 17:08:40.191 [error] <0.482.0> Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.48>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:55550 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.485.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 17:08:45.633 [error] <0.470.0>@gen_server:call gen_server 'Elixir.RabbitHandler' terminated with reason: no such process or port in call to gen_server:call(<0.484.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 17:08:45.646 [error] <0.470.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.484.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 17:08:45.646 [error] <0.341.0>@gen_server:call Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.470.0> exit with reason no such process or port in call to gen_server:call(<0.484.0>, {close,200,<<"Goodbye">>}, 60000) in context child_terminated
2020-06-02 17:10:15.039 [error] <0.513.0>@lists:reverse:147 Supervisor {<0.513.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.52>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.515.0>, {<<"client 127.0.0.1:55555 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.516.0> exit with reason no function clause matching lists:reverse(nil) line 147 in context child_terminated
2020-06-02 17:10:15.040 [error] <0.513.0> Supervisor {<0.513.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.52>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.515.0>, {<<"client 127.0.0.1:55555 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.516.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 17:10:15.041 [error] emulator Error in process <0.516.0> with exit value:
{function_clause,[{lists,reverse,[nil],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,340}]},{rabbit_writer,internal_send_command_async,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,371}]},{rabbit_writer,handle_message,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,238}]},{rabbit_writer,mainloop1,2,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,222}]},{rabbit_writer,mainloop,2,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]}]}
2020-06-02 17:11:51.943 [error] <0.503.0>@gen_server:call gen_server 'Elixir.RabbitHandler' terminated with reason: no such process or port in call to gen_server:call(<0.515.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 17:11:51.945 [error] <0.503.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.515.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 17:11:51.946 [error] <0.341.0>@gen_server:call Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.503.0> exit with reason no such process or port in call to gen_server:call(<0.515.0>, {close,200,<<"Goodbye">>}, 60000) in context child_terminated
2020-06-02 17:12:27.354 [error] <0.454.0>@lists:reverse:147 Supervisor {<0.454.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.456.0>, {<<"client 127.0.0.1:55581 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.457.0> exit with reason no function clause matching lists:reverse(nil) line 147 in context child_terminated
2020-06-02 17:12:27.354 [error] <0.454.0> Supervisor {<0.454.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.456.0>, {<<"client 127.0.0.1:55581 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.457.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 17:12:27.355 [error] emulator Error in process <0.457.0> with exit value:
{function_clause,[{lists,reverse,[nil],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,340}]},{rabbit_writer,internal_send_command_async,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,371}]},{rabbit_writer,handle_message,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,238}]},{rabbit_writer,mainloop1,2,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,222}]},{rabbit_writer,mainloop,2,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]}]}
2020-06-02 17:13:31.437 [error] <0.480.0>@lists:reverse:147 CRASH REPORT Process <0.480.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(nil) line 147
2020-06-02 17:13:31.437 [error] <0.477.0>@lists:reverse:147 Supervisor {<0.477.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.50>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.479.0>, {<<"client 127.0.0.1:55591 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.480.0> exit with reason no function clause matching lists:reverse(nil) line 147 in context child_terminated
2020-06-02 17:13:31.438 [error] <0.477.0> Supervisor {<0.477.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.50>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.479.0>, {<<"client 127.0.0.1:55591 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.480.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 17:13:37.856 [error] <0.465.0>@gen_server:call gen_server 'Elixir.RabbitHandler' terminated with reason: no such process or port in call to gen_server:call(<0.479.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 17:13:37.873 [error] <0.465.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitHandler' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.479.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 246
2020-06-02 17:13:37.874 [error] <0.336.0>@gen_server:call Supervisor 'Elixir.Redeal.Supervisor' had child 'Elixir.Redeal.RabbitHandler' started with 'Elixir.Redeal.RabbitHandler':start_link([]) at <0.465.0> exit with reason no such process or port in call to gen_server:call(<0.479.0>, {close,200,<<"Goodbye">>}, 60000) in context child_terminated
2020-06-02 17:14:44.771 [error] <0.482.0>@lists:reverse:147 Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.48>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:55597 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.485.0> exit with reason no function clause matching lists:reverse(nil) line 147 in context child_terminated
2020-06-02 17:14:44.772 [error] <0.482.0> Supervisor {<0.482.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.48>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.484.0>, {<<"client 127.0.0.1:55597 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.485.0> exit with reason reached_max_restart_intensity in context shutdown
2020-06-02 17:14:44.772 [error] emulator Error in process <0.485.0> with exit value:
{function_clause,[{lists,reverse,[nil],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,340}]},{rabbit_writer,internal_send_command_async,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,371}]},{rabbit_writer,handle_message,3,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,238}]},{rabbit_writer,mainloop1,2,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,222}]},{rabbit_writer,mainloop,2,[{file,"/Users/krzysztofmakiela/studia/komponentowe/projekt/redeal/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]}]}
2020-06-02 17:27:51.237 [error] <0.339.0> Failed to start Ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-06-02 17:29:44.377 [error] <0.339.0> Failed to start Ranch listener 'Elixir.RedealWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,4000}]) for reason eaddrinuse (address already in use)
2020-06-02 17:47:34.723 [error] <0.320.0> Supervisor 'Elixir.RedealWeb.Endpoint' had child 'Elixir.Plug.Cowboy.Drainer' started with 'Elixir.Plug.Cowboy.Drainer':start_link([{refs,['Elixir.RedealWeb.Endpoint.HTTP']}]) at <0.440.0> exit with reason killed in context shutdown_error
